---
name: Lint

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579 # v2.2
        with:
          check_hidden: false
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3
        with:
          file_or_dir: "./"
          config_file: "./.yaml-lint.yaml"
          strict: true

      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          enable-cache: true
          cache-dependency-glob: "requirements_dev.txt"
          activate-environment: true
      - name: Install dependencies
        run: |
          uv pip install -r requirements_dev.txt

      - name: Run Ruff Check
        run: |
          ruff check --output-format=github .

      - name: Run Ruff Format
        run: |
          ruff format .

      - name: Static typing with ty
        run: |
          ty check . --ignore unresolved-import
