---
name: Lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - uses: codespell-project/actions-codespell@master
    - uses: chartboost/ruff-action@v1.0.0
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Static typing with mypy
      run: |
        mypy --install-types --non-interactive --no-warn-unused-ignores .
